function perf = svmmrmr_class_accuracy(labels_true, labels_pred, varargin)
%SVMMRMR_CLASS_ACCURACY classification accuracy for SVMMRMR output
%   SVMMRMR_CLASS_ACCURACY classification accuracy for SVMMRMR output data
%   generated by bricks.lattice_feature_matrix and bricks.features_validate
%
%   Input
%   -----
%   labels_true (vector)
%       true labels for each sample, i.e. class_labels field of output from
%       bricks.lattice_feature_matrix
%   labels_pred (vector)
%       predicted labels for each sample, i.e. predictions field of
%       output from bricks.features_validate
%
%   Parameters
%   ----------
%   verbosity (0,1, default = 0)
%       verbosity level

p = inputParser;
addRequired(p,'labels_true',@isvector);
addRequired(p,'labels_pred',@isvector);
addParameter(p,'verbosity',0,@(x) x >= 0 && x <= 1);
parse(p,labels_true,labels_pred,varargin);

perf = sum(p.Results.labels_true == p.Results.labels_pred)/length(p.Results.labels_true);

if p.Results.verbosity > 0
    fprintf('classification accuracy: %0.2f%%\n',perf*100);
end

end