function [name,order] = get_atlas_region_aal(label)

name = '';
order = [];
switch label
    case {'Frontal Sup L','Frontal Sup R',...
            'Frontal Sup Orb L','Frontal Sup Orb R',...
            'Frontal Mid L','Frontal Mid R',...
            'Frontal Mid Orb L','Frontal Mid Orb R',...
            'Frontal Inf Oper L','Frontal Inf Oper R',...
            'Frontal Inf Tri L','Frontal Inf Tri R',...
            'Frontal Inf Orb L','Frontal Inf Orb R',...
            'Frontal Sup Medial L','Frontal Sup Medial R',...
            'Frontal Med Orb L','Frontal Med Orb R',...
            'Rolandic Oper L','Rolandic Oper R',...
            'Rectus L','Rectus R',...
            'Olfactory L','Olfactory R'}
        name = 'Prefrontal';
        order = 1;
        
    case {'Precentral L','Precentral R',...
            'Supp Motor Area L','Supp Motor Area R'}
        name = 'Motor';
        order = 2;
        
    case {'Pallidum L','Pallidum R',...
            'Caudate L','Caudate R',...
            'Putamen L','Putamen R',...
            'Thalamus L','Thalamus R'}
        name = 'Basal Ganglia';
        order = 3;
        
    case {'Insula L','Insula R'}
        name = 'Insula';
        order = 4;
        
    case {'Parietal Sup L','Parietal Sup R',...
            'Parietal Inf L','Parietal Inf R',...
            'SupraMarginal L','SupraMarginal R',...
            'Angular L','Angular R',...
            'Precuneus L','Precuneus R',...
            'Postcentral L','Postcentral R',...
            'Paracentral Lobule L','Paracentral Lobule R',}
        name = 'Parietal';
        order = 5;
        
    case {'Temporal Mid R','Temporal Mid L',...
            'Temporal Inf R','Temporal Inf L',...
            'Temporal Pole Sup R','Temporal Pole Sup L',...
            'Temporal Pole Mid R','Temporal Pole Mid L'...
            'Temporal Sup R','Temporal Sup L',...
            'Heschl L','Heschl R'}
        name = 'Temporal';
        order = 6;
        
    case {'Occipital Sup L','Occipital Sup R',...
            'Occipital Mid L','Occipital Mid R',...
            'Occipital Inf L','Occipital Inf R',...
            'Cuneus L','Cuneus R',...
            'Fusiform L','Fusiform R',...
            'Lingual L','Lingual R',...
            'Calcarine L','Calcarine R'}
        name = 'Occipital';
        order = 7;
        
    case {'Hippocampus L','Hippocampus R',...
            'ParaHippocampal L','ParaHippocampal R',...
            'Amygdala L','Amygdala R',...
            'Cingulum Ant L','Cingulum Ant R',...
            'Cingulum Mid L','Cingulum Mid R',...
            'Cingulum Post L','Cingulum Post R'}
        name = 'Limbic';
        order = 8;
        
    case {'Cerebelum Crus1 L','Cerebelum Crus1 R',...
            'Cerebelum Crus2 L','Cerebelum Crus2 R',...
            'Cerebelum 3 L','Cerebelum 3 R',...
            'Cerebelum 4 5 L','Cerebelum 4 5 R',...
            'Cerebelum 6 L','Cerebelum 6 R',...
            'Cerebelum 7b L','Cerebelum 7b R',...
            'Cerebelum 8 L','Cerebelum 8 R',...
            'Cerebelum 9 L','Cerebelum 9 R',...
            'Cerebelum 10 L','Cerebelum 10 R',...
            'Vermis 1 2',...
            'Vermis 3',...
            'Vermis 4 5',...
            'Vermis 6',...
            'Vermis 7',...
            'Vermis 8',...
            'Vermis 9',...
            'Vermis 10'}
        name = 'Cerebellum';
        order = 9;
        
    otherwise
        fprintf('%s not assigned\n',label);
end

end