%% pdc_analysis_blade

% pdc_analysis_s3_std
pdc_analysis_s3_std_perms
pdc_analysis_s3_std_surrogate
% pdc_analysis_s3_std_100trials
pdc_analysis_s3_std_100trials_perms
% pdc_analysis_s3_std_100trials_surrogate

% pdc_analysis_s5_std
% pdc_analysis_s5_std_perms
% pdc_analysis_s5_std_100trials

% pdc_analysis_s09_std
% pdc_analysis_s09_std_100trials

% pdc_analysis_s13_std
% pdc_analysis_s13_std_100trials

%% no envelope

% pdc_analysis_s3_std_noenv
pdc_analysis_s3_std_perms_noenv
pdc_analysis_s3_std_surrogate_noenv
% pdc_analysis_s3_std_100trials_noenv
pdc_analysis_s3_std_100trials_perms_noenv
pdc_analysis_s3_std_100trials_surrogate_noenv

% pdc_analysis_s5_std_100trials_noenv

% pdc_analysis_s09_std_100trials_noenv
