%% pdc_analysis_blade

% pdc_analysis_s3_std
% pdc_analysis_s3_std_perms
pdc_analysis_s3_std_100trials

% pdc_analysis_s5_std
% pdc_analysis_s5_std_perms
pdc_analysis_s5_std_100trials

pdc_analysis_s3_std_bootstrap