function plot_svmmrmr_confusion(labels_true, labels_pred)
%PLOT_SVMMRMR_CONFUSION plot confusion matrix for SVMMRMR output
%   PLOT_SVMMRMR_CONFUSION plot confusion matrix for SVMMRMR output data
%   generated by bricks.lattice_feature_matrix and bricks.features_validate
%
%   Input
%   -----
%   labels_true (vector)
%       true labels for each sample, i.e. class_labels field of output from
%       bricks.lattice_feature_matrix
%   labels_pred (vector)
%       predicted labels for each sample, i.e. predictions field of
%       output from bricks.features_validate

p = inputParser;
addRequired(p,'labels_true',@isvector);
addRequired(p,'labels_pred',@isvector);
parse(p,labels_true,labels_pred);

% plot confusion matrix
[confusion_mat, confusion_order] = confusionmat(p.Results.labels_true, p.Results.labels_pred);

heatmap(confusion_mat, confusion_order, confusion_order, 1,...
    'Colormap','red','ShowAllTicks',1,'UseLogColorMap',true,'Colorbar',true);

end
